black jack
Ibadichan/Black-Jack pull request #1
Opened 2017-04-08 20:02 UTC by Ibadichan

2017-04-09 11:59 UTC, vkurennov requested changes

2017-04-09 11:59 UTC, vkurennov commented on arm.rb
> +class ARM
Что такое ARM?

2017-04-09 11:59 UTC, vkurennov commented on main.rb
> +class GAME
Вообще, в ruby принято назвывть классы так: Game, Player и т.п. Полностью заглавными пишутся только константы.

2017-04-09 11:59 UTC, vkurennov commented on main.rb
> +    @player = ARM.new
Почему игрок и дилер инстансы непонятного класса ARM, а не других классов, напрмер Player и  Dealer?

2017-04-09 11:59 UTC, vkurennov commented on main.rb
> +class GAME
У тебя этот класс имеет анти-паттерн GodObject, то есть это объект, который знает и делает все. Это не ООП-подход, а обычный процедурный, обернутый в класс. Раздели его на сущности с методами: есть игрок, есть дилер, они что-то общее имеют, что-то различное (наследование), есть карта, есть колода, есть банк и т.п.

2017-04-09 11:59 UTC, vkurennov commented on main.rb
> +class GAME
У класса должна быть одна ответственность, у тебя же здесь их множество: и картами управляет, и интерфейс и банк и подсчет очков. Вот все это нужно разделить на разные объекты

2017-04-09 17:52 UTC, vkurennov requested changes

2017-04-09 17:52 UTC, vkurennov commented on main.rb
> +    if people == 'player'
А зачем делать if/else, если фактически, тут код одинаковый? Почему бы не передавать игрока как параметр?

2017-04-09 17:52 UTC, vkurennov commented on main.rb
> +  def give_out_cards
Вообще, выдавать карты - это тоже задача дилера

2017-04-09 17:52 UTC, vkurennov commented on main.rb
> +      @count += 10 if card.length > 3 && card.length != 4
Что такое card.length? Длиня массива? почему тогда мы добавляем 10 очков, если там больше 3-х карт? Ведь надо считать номинал карты.

2017-04-09 17:52 UTC, vkurennov commented on main.rb
> +  def move_of_dealer
Раз это ход дилера, то пусть и находится эта логика в соответсвующем классе.

2017-04-09 17:52 UTC, vkurennov commented on dealer.rb
> +    @methods = %w(skip_a_move add_card open_all_cards)
В чем смысл объявления этих "методов" без их реализации в самом классе? Почему какой-то внешний класс содержит логику работы дилера?

2017-04-09 17:52 UTC, vkurennov commented on main.rb
> +       @player.bank += 20
Я бы рекомендовал не вводить конкретные значения, а вычилсять их на основе ставок (минимальную ставку можно сделать константой).

2017-04-09 17:52 UTC, vkurennov commented on main.rb
> +puts ''
Всю интерфейсную часть нужно тоже вынести в отдельный класс.

2017-04-11 06:59 UTC, webmstk requested changes

2017-04-11 06:59 UTC, webmstk commented on dealer.rb
> +      element = @deck.all_cards[rand(@deck.all_cards.length)]
Лучше просто перемешать массив карт при инициализации колоды, а не высчитывать каждый раз случайное число.

2017-04-11 06:59 UTC, webmstk commented on deck.rb
> +    @all_cards = []
просто `@cards`

2017-04-11 06:59 UTC, webmstk commented on dealer.rb
> +      element = @deck.all_cards[rand(@deck.all_cards.length)]
Вместо непоределённого `element` можно назвать понятнее - `card`. Это же карта :)

2017-04-11 06:59 UTC, webmstk commented on dealer.rb
> +      @deck.all_cards.delete(element)
Эта процедура взятия карты и удаления её из колоды должна быть атомарной операцией - сделай у колоды метод "дать карту".

2017-04-11 06:59 UTC, webmstk commented on dealer.rb
> +      @deck.all_cards.delete(element)
В цикле происходят два очень похожих действия. Задумайся над возможностью вынести повторяющийся код в отдельный метод.

2017-04-11 06:59 UTC, webmstk commented on game.rb
> +    @deck = Deck.new
Мне кажется, логичнее было бы создавать колоду именно при инициализации.

2017-04-11 06:59 UTC, webmstk commented on users.rb
> +    @methods = %w(skip_a_move add_card open_all_cards)
Я бы сделал это константой. Эти методы же одинаковые для всех объектов класса. А вызов будет вместо
```
game.player.methods.include?(method)
```
такой
```
Users::METHODS.include?(method)
```

2017-04-11 06:59 UTC, webmstk commented on score.rb
> +    @count = 0
незачем делать это инстанс переменной, она используется только локально

2017-04-11 06:59 UTC, webmstk commented on score.rb
> +      @count += card.to_i # если карта не картинка, преобразовываю к int и добавляю
Тут не очень хорошо получилось, если мы определили, что карта - это валет, всё-равно будут проверятся остальные условия и преобразование к числу. Лучше выдели логику определения очков карты в отдельный метод.

2017-04-11 06:59 UTC, webmstk commented on score.rb
> +class Score
Это больше похоже на модуль, создавать объект `score = Score.new` не имеет большого смысла. Удобнее будет использование типа `Score.count(cards)`

2017-04-11 06:59 UTC, webmstk commented on score.rb
> +      @count += card.to_i # если карта не картинка, преобразовываю к int и добавляю
```
module Score
  def self.count(cards)
    cards.reduce(0) do |count, card|
      card_rank = card[0..-2]
      count += card_value(card_rank, count)
    end
  end

  private

  def self.card_value(rank, count)
    return 10 if ['Jack', 'Queen', 'King'].include? rank
    return count > 10 ? 1 : 11 if rank == 'Ace'
    rank.to_i
  end
end
```

2017-04-11 12:05 UTC, webmstk commented on deck.rb
> +    @cards.delete_at(index)
Индекс не нужен. Снимай с конца колоды через `pop` :)

2017-04-11 12:10 UTC, vkurennov requested changes

2017-04-11 12:10 UTC, vkurennov commented on dealer.rb
> +      player.cards << @deck.cards[0] << @deck.cards[1]
Лучше сделать через цикл times, так будет меньше дублирования

2017-04-11 12:10 UTC, vkurennov commented on deck.rb
> +  def give_a_card(index)
По идее, мы выдаем карту первую из колоды, а не по номеру, иначе так можно жульничать. Поэтому тут подошел бы метод `pop`, который удаляет из массива первый элемент и возвращает его. Тогда вообще с индексами не пришлось бы мучаться

2017-04-11 12:10 UTC, vkurennov commented on interface.rb
> +  if Users::METHODS.include?(method) && method == 'add_card'
А зачем каждый раз проверять включение метода в константу, если у тебя перед этим есть блок, который не дает ввести неверную команду?

2017-04-11 12:10 UTC, vkurennov commented on users.rb
> +class Users
Лучше User

2017-04-11 12:12 UTC, webmstk commented on dealer.rb
> +      @deck.give_a_card(1)
Всё проще. метод `give_a_card` уже делает всё, что нужно. `delete_at` возвращает удалённую карту, поэтому ты можешь спокойно писать
```
player.cards << @deck.give_a_card(0)
```
а если будешь использовать `pop` вместо `delete_at` (см коммент в методе), то будет ещё круче
```
2.times { player.cards << @deck.give_a_card }
```

2017-04-11 12:15 UTC, webmstk commented on dealer.rb
> +      @deck.give_a_card(1)
Суть в том, что нельзя разделять получение и удаление карты из колоды. Это должна быть единая операция. Оба этих действия сейчас объединены в методе `@deck.give_a_card`. Это понятно или подробнее объяснить?

2017-04-11 12:25 UTC, webmstk commented on deck.rb
> +  def give_a_card(index)
`pop` - это последний элемент (зануда)

2017-04-11 18:56 UTC, webmstk commented on score.rb
> +      card = card[0..-2]
Старайся не изменять смысл переменной. Создай новую переменную или сразу передавай в метод нужное значение
```
count += card_value(card[0..-2], count)
```

2017-04-11 18:57 UTC, webmstk commented on user.rb
> +    @deck = deck
Зачем это делать инстанс переменной? Где ещё она используется?

2017-04-12 08:13 UTC, vkurennov commented on deck.rb
> +  def give_a_card(index)
Ну смотря как держать колоду ;-)

2017-04-12 08:17 UTC, vkurennov approved these changes

2017-04-12 08:17 UTC, vkurennov commented on dealer.rb
> +      2.times do
Раз тут в блоке одна строка, то можно было бы как однострочник записать:

`2.times { player.cards << @deck.give_a_card }`

2017-04-12 08:17 UTC, vkurennov commented on user.rb
> +    deck.give_a_card(0)
У тебя метод `give_a_card` больше не принимает аргумент, тут ошибка будет. Ну и сам алгоритм можно написать в одну строку:

`self.cards << deck.give_a_card`

2017-04-12 08:45 UTC, webmstk commented on deck.rb
> +  def give_a_card(index)
туше :)

2017-04-12 10:38 UTC, merged